### PR TITLE
Update playground-elements

### PR DESCRIPTION
**Pull request by taylor-vann**
Update playground-elements to `0.16.3` to include JSX and TSX syntax highlighting.

### CODE REVIEW

**Comment by AndrewJakubowicz** [comment]
The build and preview deploy is broken.
It looks like the `SourceFile` type between `@lit/ts-transformers` and `typescript` is incompatible:
https://github.com/lit/lit.dev/runs/7640278509?check_suite_focus=true#step:9:128

Is it possible two different incompatible typescript versions are being used?

**Comment by aomarks** [comment]
Looks like this probably upgrades everything? Probably some new incompatibility introduced, could be totally unrelated to playground-elements. I would suggest reverting to the previous `package-lock.json`, and then bumping the playground-elements version in the `package.json`, and then running `npm i`. That should only upgrade playground-elements.

**Comment by taylor-vann** [comment]
it is totally possible!
im gonna remove my my changes and try again @AndrewJakubowicz

**Comment by aomarks** [comment]
> Looks like this probably upgrades everything? Probably some new incompatibility introduced, could be totally unrelated to playground-elements. I would suggest reverting to the previous `package-lock.json`, and then bumping the playground-elements version in the `package.json`, and then running `npm i`. That should only upgrade playground-elements.

I think you could also try `npm update playground-elements`

**Comment by taylor-vann** [comment]
nice! the "just updating playground elements" seems to have worked well

**Review by aomarks — APPROVED** [review]
Confirmed JSX and TSX highlighting is happening in the latest preview. Nice!

**Review by AndrewJakubowicz — APPROVED** [review]
Nice!

**Comment by taylor-vann** [comment]
Thanks @aomarks for all the help on this one!

**Pull request merged**
