### PR TITLE
Launch gists and remove old share button

### PR DESCRIPTION
**Pull request by aomarks**
Enables the GitHub Gists integration for everyone, without a mod.

image

Fixes https://github.com/lit/lit.dev/issues/533

Filed https://github.com/lit/lit.dev/issues/810 to track further improvements to the UI.

### CODE REVIEW

**Review by AndrewJakubowicz — APPROVED** [review]
Tested manually on Chrome. I think the only nitpick I realized while testing this is that if you use the shortcut `cmd+S` the focus remains in the editor, so it's not possible to use tab and enter to navigate the popup (between copy url and the github button).

**Review by sorvell — APPROVED** [review]
Love it!

**Review by e111077 — APPROVED** [review]

**Review by e111077 — APPROVED** [review]

**Comment by aomarks** [comment]
> Tested manually on Chrome. I think the only nitpick I realized while testing this is that if you use the shortcut `cmd+S` the focus remains in the editor, so it's not possible to use tab and enter to navigate the popup (between copy url and the github button).

Done, using `delegatesFocus`. It doesn't seem to work in Firefox, even though everything seems to indicate that Firefox supports `delegatesFocus`. Works fine in Chrome and Safari...

**Comment by e111077** [comment]
so goes the tale of delegatesFocus

**Comment by aomarks** [comment]
> so goes the tale of delegatesFocus

There seem to be no issues filed about it not working correctly. https://bugzilla.mozilla.org/show_bug.cgi?id=1413836 is marked fixed since Firefox 94.

Am I using it wrong?

**Review by AndrewJakubowicz — APPROVED** [review]
This is an improvement! We may just need to track an issue to follow up on Firefox.

**Comment by aomarks** [comment]
> This is an improvement! We may just need to track an issue to follow up on Firefox.

Yeah, https://bugzilla.mozilla.org/show_bug.cgi?id=1735667 seems like it is this issue, but it's also been marked fixed since 94 as well.

**Comment by aomarks** [comment]
> Yeah, https://bugzilla.mozilla.org/show_bug.cgi?id=1735667 seems like it is this issue, but it's also been marked fixed since 94 as well.

Commented at https://bugzilla.mozilla.org/show_bug.cgi?id=1735667#c10 with a repro

**Pull request merged**
