### PR TITLE
typo on 'Arrray'

### PR DESCRIPTION
**Pull request by drewp**

### CODE REVIEW

**Review by simi — APPROVED** [review]

**Comment by drewp** [comment]
https://cla.developers.google.com/clas says I have a CLA. You also may be able to verify that my corp GH account 'drewpca' is related to this one.

**Comment by aomarks** [comment]
> https://cla.developers.google.com/clas says I have a CLA. You also may be able to verify that my corp GH account 'drewpca' is related to this one.

Thanks for the PR! It looks like the email address you used to author this commit is not registered with the Google CLA, though. Could you agree to the CLA again using the same email address, or change the email address on the commit to match the one that has?

**Comment by drewp** [comment]
Ok, I changed my home google account to have 'contact email'=='about me emails'=='drewp@bigasterisk.com'. The CLA page does not show that email yet, and I cannot change the email on the CLA page. Maybe it will refresh after a while. 
I also set my GH profile email to drewp@bigasterisk.com. I don't know if that affects the already-proposed PR or not.
If another refresh doesn't work, let's give up and I'll resubmit from corp.

**Review by AndrewJakubowicz — APPROVED** [review]
Thank you!

**Comment by AndrewJakubowicz** [comment]
LGTM on https://pr633-7372550---lit-dev-5ftespv5na-uc.a.run.app/docs/components/properties/#conversion-type

**Pull request merged**
