### PR TITLE
responsive css for images in blog posts

### PR DESCRIPTION
**Pull request by jaydanurwin**
Fixes issue #701

### CODE REVIEW

**Comment by aomarks** [comment]
> Fixes issue #701

Thanks for the PR! It looks like you haven't signed the Google CLA, see https://github.com/lit/lit.dev/pull/702/checks?check_run_id=5162147276

**Comment by jaydanurwin** [comment]
No problem! I just signed it. Let me know if I need to do anything else! 👍🏼

**Comment by aomarks** [comment]
Fix is live at https://lit.dev/blog/2022-02-07-eleventy/. Thanks again!

**Comment by jaydanurwin** [comment]
Awesome, of course!

**Pull request merged**
